// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgTCFp7e7qoJj_6xUaTrjyWtrlXtFIUro',
    appId: '1:366583602195:web:6cb3134c8c8ad28d55f3e6',
    messagingSenderId: '366583602195',
    projectId: 'maribermusik-752',
    authDomain: 'maribermusik-752.firebaseapp.com',
    storageBucket: 'maribermusik-752.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6V4Qo9xVSIkC9Pdx1VITtU-Co0gHUg4c',
    appId: '1:366583602195:android:7bd5c93a5dee5edc55f3e6',
    messagingSenderId: '366583602195',
    projectId: 'maribermusik-752',
    storageBucket: 'maribermusik-752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOg5p-o0ZmNVSNrlOpg5FEooM4EkDXyek',
    appId: '1:366583602195:ios:28df70bfa97cab8755f3e6',
    messagingSenderId: '366583602195',
    projectId: 'maribermusik-752',
    storageBucket: 'maribermusik-752.appspot.com',
    iosBundleId: 'com.example.mariBermusik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOg5p-o0ZmNVSNrlOpg5FEooM4EkDXyek',
    appId: '1:366583602195:ios:9e7cc4b4c13d876755f3e6',
    messagingSenderId: '366583602195',
    projectId: 'maribermusik-752',
    storageBucket: 'maribermusik-752.appspot.com',
    iosBundleId: 'com.example.mariBermusik.RunnerTests',
  );
}
